import React from "react";
import Head from "next/head";
import "../styles/global.scss";

export const metadata = {
  title: "Portfolio 2",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Head>
        <title>{metadata.title}</title>
        <meta name='description' content={metadata.description} />
      </Head>
      <body>{children}</body>
    </html>
  );
}
